name: 4. Setup Python Action

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4
        
      - name: 파이썬 설치하기
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: 파이썬 코드 실행하기
        run: python -c "print('GitHub Actions에서 파이썬이 정상적으로 실행됩니다!')"
